### ISSUE TITLE
Potential Issue

### ISSUE THREAD

**Issue by dcRUSTy** [techygarg/ConfIT#1]
https://github.com/techygarg/ConfIT/blob/0c5afc4a0dc8bad338c308756119ff0fe030ceb5/.github/workflows/build.yml#L68-L71
IMO Under some circumstances in future where branch name contains "/tags/v" anywhere in name might lead to something unexpected.

**Comment by techygarg** [comment]
Thanks @dcRUSTy. Yes, that might be a possible issue. I have added a branch filter to take care the same.
