### ISSUE TITLE
Projects without startup.cs

### ISSUE THREAD

**Issue by tamazbagdavadze** [techygarg/ConfIT#3]
Is it possible to use this library without start up class? In the net6 there is no startup.cs any more.

**Comment by techygarg** [comment]
Hi @tamazbagdavadze , currently it support with Startup.cs only.  

We have to override several API features, which we don't need or need different implementation in local integrations tests. For e.g.: in memory database, swagger, secret storage tools etc. 

With current implementation, we make these method as virtual in API startup.cs and override these behaviours in our tests  startup.cs. 

We may use configurations to switch on/ff these, but I don't want to add configurations just for tests in my production code, so I believe startup class still a better way handle these all things.

I will explore more how we can achieve all these without startup class.
